### ISSUE TITLE
403 error on new 7.1.61 Unifi Network on cloud key Gen2 and Invalid CSRF Token

### ISSUE THREAD

**Issue by NebzHB** [jens-maus/node-unifi#157]
```
ERROR startListening:  Error: Request failed with status code 403
at createError (/var/www/html/plugins/unifi/resources/node_modules/node-unifi/node_modules/axios/lib/core/createError.js:16:15)
at settle (/var/www/html/plugins/unifi/resources/node_modules/node-unifi/node_modules/axios/lib/core/settle.js:17:12)
at /var/www/html/plugins/unifi/resources/node_modules/node-unifi/node_modules/axios-cookiejar-support/lib/interceptors/response.js:83:25
at new Promise ()
at responseInterceptor (/var/www/html/plugins/unifi/resources/node_modules/node-unifi/node_modules/axios-cookiejar-support/lib/interceptors/response.js:82:9)
at /var/www/html/plugins/unifi/resources/node_modules/node-unifi/node_modules/axios-cookiejar-support/lib/index.js:130:67
at processTicksAndRejections (internal/process/task_queues.js:95:5) {
config: {
url: 'https://192.168.1.8/proxy/network/dl/firmware/bundles.json',
method: 'post',
data: '{}',
headers: {
Accept: 'application/json, text/plain, */*',
'X-CSRF-Token': 'aaaaaaa-9306-4bdf-9b45-151134d8c7df',
'Content-Type': 'application/json',
Cookie: 'TOKEN=AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA.eyJ1c2VySWQiOiIwNWE5YWJiMi1hYmE1LTQ1YjMtYTc2MS0wOWJlYjQ2YWU2NDEiLCJjc3JmVG9rZW4iOiIwYjdhZDU2ZS1hYmU5LTQ3N2MtYjRjNS0wNDllZTU4MzQ4ZTUiLCJqdGkiOiIwZmFkN2E5Ni1hYmNkLTQ3YjAtODZmNy1iYjEzMWM5MjYxODYiLCJwYXNzd29yZFJldmlzaW9uIjoxNjEyMzEwNjQ2LCJpYXQiOjE2NTIyMjE1MDgsImV4cCI6MTY1MjIyNTEwOH0.bWzGkzRyb51_PGuZsa7oexvP9f-8ORtdNfqNcnky8BM',
'User-Agent': 'axios/0.21.4',
'Content-Length': 2
},
transformRequest: [ [Function: transformRequest] ],
transformResponse: [ [Function: transformResponse] ],
timeout: 0,
withCredentials: true,
adapter: [Function: httpAdapter],
xsrfCookieName: 'XSRF-TOKEN',
xsrfHeaderName: 'X-XSRF-TOKEN',
maxContentLength: -1,
maxBodyLength: -1,
httpsAgent: Agent {
_events: [Object: null prototype],
_eventsCount: 2,
_maxListeners: undefined,
defaultPort: 443,
protocol: 'https:',
options: [Object],
requests: {},
sockets: {},
freeSockets: [Object],
keepAliveMsecs: 1000,
keepAlive: true,
maxSockets: Infinity,
maxFreeSockets: 256,
scheduling: 'lifo',
maxTotalSockets: Infinity,
totalSocketCount: 0,
maxCachedSessions: 100,
_sessionCache: [Object],
[Symbol(kCapture)]: false
},
transitional: {
silentJSONParsing: true,
forcedJSONParsing: true,
clarifyTimeoutError: false
},
jar: CookieJar {
rejectPublicSuffixes: true,
enableLooseMode: false,
allowSpecialUseDomain: false,
store: { idx: {
'192.168.1.8': {
'/': {
TOKEN: Cookie="TOKEN=AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA.eyJ1c2VySWQiOiIwNWE5YWJiMi1hYmE1LTQ1YjMtYTc2MS0wOWJlYjQ2YWU2NDEiLCJjc3JmVG9rZW4iOiIwYjdhZDU2ZS1hYmU5LTQ3N2MtYjRjNS0wNDllZTU4MzQ4ZTUiLCJqdGkiOiIwZmFkN2E5Ni1hYmNkLTQ3YjAtODZmNy1iYjEzMWM5MjYxODYiLCJwYXNzd29yZFJldmlzaW9uIjoxNjEyMzEwNjQ2LCJpYXQiOjE2NTIyMjE1MDgsImV4cCI6MTY1MjIyNTEwOH0.bWzGkzRyb51_PGuZsa7oexvP9f-8ORtdNfqNcnky8BM; Path=/; Secure; HttpOnly; hostOnly=true; aAge=10ms; cAge=22ms"
}
}
} },
prefixSecurity: 'silent',
_cloneSync: [Function (anonymous)],
_importCookiesSync: [Function (anonymous)],
getCookiesSync: [Function (anonymous)],
getCookieStringSync: [Function (anonymous)],
getSetCookieStringsSync: [Function (anonymous)],
removeAllCookiesSync: [Function (anonymous)],
setCookieSync: [Function (anonymous)],
serializeSync: [Function (anonymous)]
},
maxRedirects: 0,
validateStatus: [Function: validateStatus]
},
request:  ClientRequest {
_events: [Object: null prototype] {
error: [Function: handleRequestError],
prefinish: [Function: requestOnPrefinish]
},
_eventsCount: 2,
_maxListeners: undefined,
outputData: [],
outputSize: 0,
writable: true,
destroyed: true,
_last: false,
chunkedEncoding: false,
shouldKeepAlive: true,
_defaultKeepAlive: true,
useChunkedEncodingByDefault: true,
sendDate: false,
_removedConnection: false,
_removedContLen: false,
_removedTE: false,
_contentLength: 2,
_hasBody: true,
_trailer: '',
finished: true,
_headerSent: true,
socket: TLSSocket {
_tlsOptions: [Object],
_secureEstablished: true,
_securePending: false,
_newSessionPending: false,
_controlReleased: true,
secureConnecting: false,
_SNICallback: null,
servername: false,
alpnProtocol: false,
authorized: false,
authorizationError: 'DEPTH_ZERO_SELF_SIGNED_CERT',
encrypted: true,
_events: [Object: null prototype],
_eventsCount: 9,
connecting: false,
_hadError: false,
_parent: null,
_host: null,
_readableState: [ReadableState],
_maxListeners: undefined,
_writableState: [WritableState],
allowHalfOpen: false,
_sockname: null,
_pendingData: null,
_pendingEncoding: '',
server: undefined,
_server: null,
ssl: [TLSWrap],
_requestCert: true,
_rejectUnauthorized: false,
parser: null,
_httpMessage: null,
timeout: 0,
[Symbol(res)]: [TLSWrap],
[Symbol(verified)]: true,
[Symbol(pendingSession)]: null,
[Symbol(async_id_symbol)]: -1,
[Symbol(kHandle)]: [TLSWrap],
[Symbol(kSetNoDelay)]: false,
[Symbol(lastWriteQueueSize)]: 0,
[Symbol(timeout)]: null,
[Symbol(kBuffer)]: null,
[Symbol(kBufferCb)]: null,
[Symbol(kBufferGen)]: null,
[Symbol(kCapture)]: false,
[Symbol(kBytesRead)]: 0,
[Symbol(kBytesWritten)]: 0,
[Symbol(connect-options)]: [Object],
[Symbol(RequestTimeout)]: undefined
},
_header: 'POST /proxy/network/dl/firmware/bundles.json HTTP/1.1
' +
'Accept: application/json, text/plain, */*
' +
'X-CSRF-Token: aaaaaaa-9306-4bdf-9b45-151134d8c7df
' +
'Content-Type: application/json
' +
'Cookie: TOKEN=AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA.eyJ1c2VySWQiOiIwNWE5YWJiMi1hYmE1LTQ1YjMtYTc2MS0wOWJlYjQ2YWU2NDEiLCJjc3JmVG9rZW4iOiIwYjdhZDU2ZS1hYmU5LTQ3N2MtYjRjNS0wNDllZTU4MzQ4ZTUiLCJqdGkiOiIwZmFkN2E5Ni1hYmNkLTQ3YjAtODZmNy1iYjEzMWM5MjYxODYiLCJwYXNzd29yZFJldmlzaW9uIjoxNjEyMzEwNjQ2LCJpYXQiOjE2NTIyMjE1MDgsImV4cCI6MTY1MjIyNTEwOH0.bWzGkzRyb51_PGuZsa7oexvP9f-8ORtdNfqNcnky8BM
' +
'User-Agent: axios/0.21.4
' +
'Content-Length: 2
' +
'Host: 192.168.1.8
' +
'Connection: keep-alive
' +
'
',
_keepAliveTimeout: 0,
_onPendingData: [Function: noopPendingOutput],
agent: Agent {
_events: [Object: null prototype],
_eventsCount: 2,
_maxListeners: undefined,
defaultPort: 443,
protocol: 'https:',
options: [Object],
requests: {},
sockets: {},
freeSockets: [Object],
keepAliveMsecs: 1000,
keepAlive: true,
maxSockets: Infinity,
maxFreeSockets: 256,
scheduling: 'lifo',
maxTotalSockets: Infinity,
totalSocketCount: 0,
maxCachedSessions: 100,
_sessionCache: [Object],
[Symbol(kCapture)]: false
},
socketPath: undefined,
method: 'POST',
maxHeaderSize: undefined,
insecureHTTPParser: undefined,
path: '/proxy/network/dl/firmware/bundles.json',
_ended: true,
res: IncomingMessage {
_readableState: [ReadableState],
_events: [Object: null prototype],
_eventsCount: 3,
_maxListeners: undefined,
socket: null,
httpVersionMajor: 1,
httpVersionMinor: 1,
httpVersion: '1.1',
complete: true,
headers: [Object],
rawHeaders: [Array],
trailers: {},
rawTrailers: [],
aborted: false,
upgrade: false,
url: '',
method: null,
statusCode: 403,
statusMessage: 'Forbidden',
client: [TLSSocket],
_consuming: false,
_dumped: false,
req: [Circular *1],
[Symbol(kCapture)]: false,
[Symbol(RequestTimeout)]: undefined
},
aborted: false,
timeoutCb: null,
upgradeOrConnect: false,
parser: null,
maxHeadersCount: null,
reusedSocket: true,
host: '192.168.1.8',
protocol: 'https:',
[Symbol(kCapture)]: false,
[Symbol(kNeedDrain)]: false,
[Symbol(corked)]: 0,
[Symbol(kOutHeaders)]: [Object: null prototype] {
accept: [Array],
'x-csrf-token': [Array],
'content-type': [Array],
cookie: [Array],
'user-agent': [Array],
'content-length': [Array],
host: [Array]
}
},
response: {
status: 403,
statusText: 'Forbidden',
headers: {
vary: 'Origin',
'x-dns-prefetch-control': 'off',
'x-frame-options': 'SAMEORIGIN',
'strict-transport-security': 'max-age=15552000; includeSubDomains',
'x-download-options': 'noopen',
'x-content-type-options': 'nosniff',
'x-xss-protection': '1; mode=block',
'accept-ranges': 'bytes',
'content-type': 'application/json; charset=utf-8',
'x-response-time': '2ms',
'content-length': '32',
date: 'Tue, 10 May 2022 22:25:09 GMT',
connection: 'keep-alive'
},
config: {
url: 'https://192.168.1.8/proxy/network/dl/firmware/bundles.json',
method: 'post',
data: '{}',
headers: [Object],
transformRequest: [Array],
transformResponse: [Array],
timeout: 0,
withCredentials: true,
adapter: [Function: httpAdapter],
xsrfCookieName: 'XSRF-TOKEN',
xsrfHeaderName: 'X-XSRF-TOKEN',
maxContentLength: -1,
maxBodyLength: -1,
httpsAgent: [Agent],
transitional: [Object],
jar: [CookieJar],
maxRedirects: 0,
validateStatus: [Function: validateStatus]
},
request:  ClientRequest {
_events: [Object: null prototype],
_eventsCount: 2,
_maxListeners: undefined,
outputData: [],
outputSize: 0,
writable: true,
destroyed: true,
_last: false,
chunkedEncoding: false,
shouldKeepAlive: true,
_defaultKeepAlive: true,
useChunkedEncodingByDefault: true,
sendDate: false,
_removedConnection: false,
_removedContLen: false,
_removedTE: false,
_contentLength: 2,
_hasBody: true,
_trailer: '',
finished: true,
_headerSent: true,
socket: [TLSSocket],
_header: 'POST /proxy/network/dl/firmware/bundles.json HTTP/1.1
' +
'Accept: application/json, text/plain, */*
' +
'X-CSRF-Token: aaaaaaa-9306-4bdf-9b45-151134d8c7df
' +
'Content-Type: application/json
' +
'Cookie: TOKEN=AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA.eyJ1c2VySWQiOiIwNWE5YWJiMi1hYmE1LTQ1YjMtYTc2MS0wOWJlYjQ2YWU2NDEiLCJjc3JmVG9rZW4iOiIwYjdhZDU2ZS1hYmU5LTQ3N2MtYjRjNS0wNDllZTU4MzQ4ZTUiLCJqdGkiOiIwZmFkN2E5Ni1hYmNkLTQ3YjAtODZmNy1iYjEzMWM5MjYxODYiLCJwYXNzd29yZFJldmlzaW9uIjoxNjEyMzEwNjQ2LCJpYXQiOjE2NTIyMjE1MDgsImV4cCI6MTY1MjIyNTEwOH0.bWzGkzRyb51_PGuZsa7oexvP9f-8ORtdNfqNcnky8BM
' +
'User-Agent: axios/0.21.4
' +
'Content-Length: 2
' +
'Host: 192.168.1.8
' +
'Connection: keep-alive
' +
'
',
_keepAliveTimeout: 0,
_onPendingData: [Function: noopPendingOutput],
agent: [Agent],
socketPath: undefined,
method: 'POST',
maxHeaderSize: undefined,
insecureHTTPParser: undefined,
path: '/proxy/network/dl/firmware/bundles.json',
_ended: true,
res: [IncomingMessage],
aborted: false,
timeoutCb: null,
upgradeOrConnect: false,
parser: null,
maxHeadersCount: null,
reusedSocket: true,
host: '192.168.1.8',
protocol: 'https:',
[Symbol(kCapture)]: false,
[Symbol(kNeedDrain)]: false,
[Symbol(corked)]: 0,
[Symbol(kOutHeaders)]: [Object: null prototype]
},
data: { message: 'Invalid CSRF Token' }
},
isAxiosError: true,
toJSON: [Function: toJSON]
}
```

**Comment by jens-maus** [comment]
Sorry, but our testframework does not show any problem/issue regarding 7.1.61. See here:

https://github.com/jens-maus/node-unifi/runs/6255467306?check_suite_focus=true#step:6:34

This shows that all tests are correctly executed with a live 7.1.61 installation running.

**Comment by NebzHB** [comment]
No issue on software controller, only on cloudkeys

**Comment by NebzHB** [comment]
it seems the file need auth on CloudKeys now...

**Comment by NebzHB** [comment]
same with logout or any action in fact...

```
ERROR Stop:  Error: Request failed with status code 403
at createError (/var/www/html/plugins/unifi/resources/node_modules/node-unifi/node_modules/axios/lib/core/createError.js:16:15)
at settle (/var/www/html/plugins/unifi/resources/node_modules/node-unifi/node_modules/axios/lib/core/settle.js:17:12)
at /var/www/html/plugins/unifi/resources/node_modules/node-unifi/node_modules/axios-cookiejar-support/lib/interceptors/response.js:83:25
at new Promise (<anonymous>)
at responseInterceptor (/var/www/html/plugins/unifi/resources/node_modules/node-unifi/node_modules/axios-cookiejar-support/lib/interceptors/response.js:82:9)
at /var/www/html/plugins/unifi/resources/node_modules/node-unifi/node_modules/axios-cookiejar-support/lib/index.js:130:67
at runMicrotasks (<anonymous>)
at processTicksAndRejections (internal/process/task_queues.js:95:5) {
config: {
url: 'https://192.168.1.8/api/auth/logout',
method: 'post',
data: null,
headers: {
Accept: 'application/json, text/plain, */*',
'X-CSRF-Token': '1bd8d85e-2e71-4d99-be44-8d2daa4b7dd7',
'Content-Type': 'application/x-www-form-urlencoded',
Cookie: 'TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwNWE5YWJiMi1hYmE1LTQ1YjMtYTc2MS0wOWJlYjQ2YWU2NDEiLCJjc3JmVG9rZW4iOiI1MzQ5MDBlMC0yMjc5LTRiZjAtYWE0Mi0xNWU3MTdhMjg5NDYiLCJqdGkiOiJkYmZmMWQwMS02ZjZjLTRkNDAtYTMyMS1mYjhhZTQxNmI0OTgiLCJwYXNzd29yZFJldmlzaW9uIjoxNjEyMzEwNjQ2LCJpYXQiOjE2NTIzNDU4NDUsImV4cCI6MTY1MjM0OTQ0NX0.MQlM5WHdZKw4hvEDc06fDNmnh6oHiZTaMO76Kx2Z3ao',
'User-Agent': 'axios/0.21.4'
},
transformRequest: [ [Function: transformRequest] ],
transformResponse: [ [Function: transformResponse] ],
timeout: 0,
withCredentials: true,
adapter: [Function: httpAdapter],
xsrfCookieName: 'XSRF-TOKEN',
xsrfHeaderName: 'X-XSRF-TOKEN',
maxContentLength: -1,
maxBodyLength: -1,
httpsAgent: Agent {
_events: [Object: null prototype],
_eventsCount: 2,
_maxListeners: undefined,
defaultPort: 443,
protocol: 'https:',
options: [Object],
requests: {},
sockets: {},
freeSockets: [Object],
keepAliveMsecs: 1000,
keepAlive: true,
maxSockets: Infinity,
maxFreeSockets: 256,
scheduling: 'lifo',
maxTotalSockets: Infinity,
totalSocketCount: 0,
maxCachedSessions: 100,
_sessionCache: [Object],
[Symbol(kCapture)]: false
},
transitional: {
silentJSONParsing: true,
forcedJSONParsing: true,
clarifyTimeoutError: false
},
jar: CookieJar {
rejectPublicSuffixes: true,
enableLooseMode: false,
allowSpecialUseDomain: false,
store: { idx: {
'192.168.1.8': {
'/': {
TOKEN: Cookie="TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwNWE5YWJiMi1hYmE1LTQ1YjMtYTc2MS0wOWJlYjQ2YWU2NDEiLCJjc3JmVG9rZW4iOiI1MzQ5MDBlMC0yMjc5LTRiZjAtYWE0Mi0xNWU3MTdhMjg5NDYiLCJqdGkiOiJkYmZmMWQwMS02ZjZjLTRkNDAtYTMyMS1mYjhhZTQxNmI0OTgiLCJwYXNzd29yZFJldmlzaW9uIjoxNjEyMzEwNjQ2LCJpYXQiOjE2NTIzNDU4NDUsImV4cCI6MTY1MjM0OTQ0NX0.MQlM5WHdZKw4hvEDc06fDNmnh6oHiZTaMO76Kx2Z3ao; Path=/; Secure; HttpOnly; hostOnly=true; aAge=9ms; cAge=24436111ms"
}
}
} },
prefixSecurity: 'silent',
_cloneSync: [Function (anonymous)],
_importCookiesSync: [Function (anonymous)],
getCookiesSync: [Function (anonymous)],
getCookieStringSync: [Function (anonymous)],
getSetCookieStringsSync: [Function (anonymous)],
removeAllCookiesSync: [Function (anonymous)],
setCookieSync: [Function (anonymous)],
serializeSync: [Function (anonymous)]
},
maxRedirects: 0,
validateStatus: [Function: validateStatus]
},
request: <ref *1> ClientRequest {
_events: [Object: null prototype] {
error: [Function: handleRequestError],
prefinish: [Function: requestOnPrefinish]
},
_eventsCount: 2,
_maxListeners: undefined,
outputData: [],
outputSize: 0,
writable: true,
destroyed: true,
_last: false,
chunkedEncoding: false,
shouldKeepAlive: true,
_defaultKeepAlive: true,
useChunkedEncodingByDefault: true,
sendDate: false,
_removedConnection: false,
_removedContLen: false,
_removedTE: false,
_contentLength: 0,
_hasBody: true,
_trailer: '',
finished: true,
_headerSent: true,
socket: TLSSocket {
_tlsOptions: [Object],
_secureEstablished: true,
_securePending: false,
_newSessionPending: false,
_controlReleased: true,
secureConnecting: false,
_SNICallback: null,
servername: false,
alpnProtocol: false,
authorized: false,
authorizationError: 'DEPTH_ZERO_SELF_SIGNED_CERT',
encrypted: true,
_events: [Object: null prototype],
_eventsCount: 9,
connecting: false,
_hadError: false,
_parent: null,
_host: null,
_readableState: [ReadableState],
_maxListeners: undefined,
_writableState: [WritableState],
allowHalfOpen: false,
_sockname: null,
_pendingData: null,
_pendingEncoding: '',
server: undefined,
_server: null,
ssl: [TLSWrap],
_requestCert: true,
_rejectUnauthorized: false,
parser: null,
_httpMessage: null,
timeout: 0,
[Symbol(res)]: [TLSWrap],
[Symbol(verified)]: true,
[Symbol(pendingSession)]: null,
[Symbol(async_id_symbol)]: -1,
[Symbol(kHandle)]: [TLSWrap],
[Symbol(kSetNoDelay)]: false,
[Symbol(lastWriteQueueSize)]: 0,
[Symbol(timeout)]: null,
[Symbol(kBuffer)]: null,
[Symbol(kBufferCb)]: null,
[Symbol(kBufferGen)]: null,
[Symbol(kCapture)]: false,
[Symbol(kBytesRead)]: 0,
[Symbol(kBytesWritten)]: 0,
[Symbol(connect-options)]: [Object],
[Symbol(RequestTimeout)]: undefined
},
_header: 'POST /api/auth/logout HTTP/1.1
' +
'Accept: application/json, text/plain, */*
' +
'X-CSRF-Token: 1bd8d85e-2e71-4d99-be44-8d2daa4b7dd7
' +
'Content-Type: application/x-www-form-urlencoded
' +
'Cookie: TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwNWE5YWJiMi1hYmE1LTQ1YjMtYTc2MS0wOWJlYjQ2YWU2NDEiLCJjc3JmVG9rZW4iOiI1MzQ5MDBlMC0yMjc5LTRiZjAtYWE0Mi0xNWU3MTdhMjg5NDYiLCJqdGkiOiJkYmZmMWQwMS02ZjZjLTRkNDAtYTMyMS1mYjhhZTQxNmI0OTgiLCJwYXNzd29yZFJldmlzaW9uIjoxNjEyMzEwNjQ2LCJpYXQiOjE2NTIzNDU4NDUsImV4cCI6MTY1MjM0OTQ0NX0.MQlM5WHdZKw4hvEDc06fDNmnh6oHiZTaMO76Kx2Z3ao
' +
'User-Agent: axios/0.21.4
' +
'Host: 192.168.1.8
' +
'Connection: keep-alive
' +
'Content-Length: 0
' +
'
',
_keepAliveTimeout: 0,
_onPendingData: [Function: noopPendingOutput],
agent: Agent {
_events: [Object: null prototype],
_eventsCount: 2,
_maxListeners: undefined,
defaultPort: 443,
protocol: 'https:',
options: [Object],
requests: {},
sockets: {},
freeSockets: [Object],
keepAliveMsecs: 1000,
keepAlive: true,
maxSockets: Infinity,
maxFreeSockets: 256,
scheduling: 'lifo',
maxTotalSockets: Infinity,
totalSocketCount: 0,
maxCachedSessions: 100,
_sessionCache: [Object],
[Symbol(kCapture)]: false
},
socketPath: undefined,
method: 'POST',
maxHeaderSize: undefined,
insecureHTTPParser: undefined,
path: '/api/auth/logout',
_ended: true,
res: IncomingMessage {
_readableState: [ReadableState],
_events: [Object: null prototype],
_eventsCount: 3,
_maxListeners: undefined,
socket: null,
httpVersionMajor: 1,
httpVersionMinor: 1,
httpVersion: '1.1',
complete: true,
headers: [Object],
rawHeaders: [Array],
trailers: {},
rawTrailers: [],
aborted: false,
upgrade: false,
url: '',
method: null,
statusCode: 403,
statusMessage: 'Forbidden',
client: [TLSSocket],
_consuming: false,
_dumped: false,
req: [Circular *1],
[Symbol(kCapture)]: false,
[Symbol(RequestTimeout)]: undefined
},
aborted: false,
timeoutCb: null,
upgradeOrConnect: false,
parser: null,
maxHeadersCount: null,
reusedSocket: true,
host: '192.168.1.8',
protocol: 'https:',
[Symbol(kCapture)]: false,
[Symbol(kNeedDrain)]: false,
[Symbol(corked)]: 0,
[Symbol(kOutHeaders)]: [Object: null prototype] {
accept: [Array],
'x-csrf-token': [Array],
'content-type': [Array],
cookie: [Array],
'user-agent': [Array],
host: [Array]
}
},
response: {
status: 403,
statusText: 'Forbidden',
headers: {
vary: 'Origin',
'x-dns-prefetch-control': 'off',
'x-frame-options': 'SAMEORIGIN',
'strict-transport-security': 'max-age=15552000; includeSubDomains',
'x-download-options': 'noopen',
'x-content-type-options': 'nosniff',
'x-xss-protection': '1; mode=block',
'accept-ranges': 'bytes',
'content-type': 'application/json; charset=utf-8',
'x-response-time': '1ms',
'content-length': '32',
date: 'Thu, 12 May 2022 08:57:25 GMT',
connection: 'keep-alive'
},
config: {
url: 'https://192.168.1.8/api/auth/logout',
method: 'post',
data: null,
headers: [Object],
transformRequest: [Array],
transformResponse: [Array],
timeout: 0,
withCredentials: true,
adapter: [Function: httpAdapter],
xsrfCookieName: 'XSRF-TOKEN',
xsrfHeaderName: 'X-XSRF-TOKEN',
maxContentLength: -1,
maxBodyLength: -1,
httpsAgent: [Agent],
transitional: [Object],
jar: [CookieJar],
maxRedirects: 0,
validateStatus: [Function: validateStatus]
},
request: <ref *1> ClientRequest {
_events: [Object: null prototype],
_eventsCount: 2,
_maxListeners: undefined,
outputData: [],
outputSize: 0,
writable: true,
destroyed: true,
_last: false,
chunkedEncoding: false,
shouldKeepAlive: true,
_defaultKeepAlive: true,
useChunkedEncodingByDefault: true,
sendDate: false,
_removedConnection: false,
_removedContLen: false,
_removedTE: false,
_contentLength: 0,
_hasBody: true,
_trailer: '',
finished: true,
_headerSent: true,
socket: [TLSSocket],
_header: 'POST /api/auth/logout HTTP/1.1
' +
'Accept: application/json, text/plain, */*
' +
'X-CSRF-Token: 1bd8d85e-2e71-4d99-be44-8d2daa4b7dd7
' +
'Content-Type: application/x-www-form-urlencoded
' +
'Cookie: TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwNWE5YWJiMi1hYmE1LTQ1YjMtYTc2MS0wOWJlYjQ2YWU2NDEiLCJjc3JmVG9rZW4iOiI1MzQ5MDBlMC0yMjc5LTRiZjAtYWE0Mi0xNWU3MTdhMjg5NDYiLCJqdGkiOiJkYmZmMWQwMS02ZjZjLTRkNDAtYTMyMS1mYjhhZTQxNmI0OTgiLCJwYXNzd29yZFJldmlzaW9uIjoxNjEyMzEwNjQ2LCJpYXQiOjE2NTIzNDU4NDUsImV4cCI6MTY1MjM0OTQ0NX0.MQlM5WHdZKw4hvEDc06fDNmnh6oHiZTaMO76Kx2Z3ao
' +
'User-Agent: axios/0.21.4
' +
'Host: 192.168.1.8
' +
'Connection: keep-alive
' +
'Content-Length: 0
' +
'
',
_keepAliveTimeout: 0,
_onPendingData: [Function: noopPendingOutput],
agent: [Agent],
socketPath: undefined,
method: 'POST',
maxHeaderSize: undefined,
insecureHTTPParser: undefined,
path: '/api/auth/logout',
_ended: true,
res: [IncomingMessage],
aborted: false,
timeoutCb: null,
upgradeOrConnect: false,
parser: null,
maxHeadersCount: null,
reusedSocket: true,
host: '192.168.1.8',
protocol: 'https:',
[Symbol(kCapture)]: false,
[Symbol(kNeedDrain)]: false,
[Symbol(corked)]: 0,
[Symbol(kOutHeaders)]: [Object: null prototype]
},
data: { message: 'Invalid CSRF Token' }
},
isAxiosError: true,
toJSON: [Function: toJSON]
}
```

**Comment by NebzHB** [comment]
thx !

**Comment by jens-maus** [comment]
Does it work now with 2.0.5?

**Comment by NebzHB** [comment]
My users are trying, I keep you up to date when i have feedback.
