### ISSUE TITLE
Callback already called

### ISSUE THREAD

**Issue by kitzler-walli** [jens-maus/node-unifi#7]
Currently I use this library to log the dashboard data from unifi. The script runs every hour and stores the data in a mysql database. But sometimes I receive these strange error messages:

```
 Error: Callback was already called.
     at /home/stephan/nodejs/wanspeed/node_modules/async/dist/async.js:903:32
     at next (/home/stephan/nodejs/wanspeed/node_modules/async/dist/async.js:5195:25)
     at Request.<anonymous> (/home/stephan/nodejs/wanspeed/node_modules/node-unifi/unifi.js:1369:11)
     at emitOne (events.js:101:20)
     at Request.emit (events.js:191:7)
     at Request.onRequestError (/home/stephan/nodejs/wanspeed/node_modules/request/request.js:884:8)
     at emitOne (events.js:96:13)
     at ClientRequest.emit (events.js:191:7)
     at TLSSocket.socketErrorListener (_http_client.js:358:9)
     at emitOne (events.js:96:13)
```

This is the code I use to get the dashboard data:
```
controller.login("user", "password", function(err) {

	if (err) {
		console.log('ERROR: ' + err);
		return;
	}

	controller.getDashboard('default', function(err, client_data) {
		if (err) {
			console.log(err);
		}
		for (var i = 0; i < client_data[0].length; i++) {
			//database stuff...
		}

		controller.logout();

	}.bind({
		conn: conn
	}));
});
```

Is there a problem with my code?

**Comment by jens-maus** [comment]
This should be fixed by having integrated PR #9
